version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: crypto_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 132
      POSTGRES_DB: crypto_db
    ports:
      - "5432:5432"

  api:
    build: .
    container_name: crypto_api
    restart: always
    depends_on:
      - postgres
    ports:
      - "5000:5000"

  fetcher:
    build: .
    container_name: crypto_fetcher
    restart: always
    depends_on:
      - postgres
    command: python fetch_crypto.py